name: Update JSON File

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the action every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests pandas PyGithub

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python research/odds_data_webpage_api_code.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add research/output7.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update JSON data" && git push)
